---
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: test-cluster
  region: ap-south-1

fargateProfiles:
  - name: fp-custom
    selectors:
      - namespace: workshop
        labels:
          app: prodcatalog
      - namespace: prodcatalog-ns
      - namespace: kube-system
      - namespace: default 
      - namespace: appmesh-system
      - namespace: aws-observability

