apiVersion: apps/v1
kind: Deployment
metadata:
  name: sidecar-logz-example
  labels:
    app: sidecar-logz-example
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sidecar-logz-example

  template:
    metadata:
      labels:
        app: sidecar-logz-example
    spec:
      serviceAccount: fluentd
      serviceAccountName: fluentd
      containers:
      - name: logzio-forwarder
        image: logzio/logzio-k8s:latest
        env:
        - name:  LOGZIO_TOKEN
          value: "VUoucIikuuiPthzYSncaHKSoXJypQZNSk"
        - name:  LOGZIO_URL
          value: "https://listener.logz.io:8071"
        resources:
          limits:
            memory: 200Mi
          requests:
            cpu: 100m
            memory: 200Mi
 
