apiVersion: apps/v1
kind: Deployment
metadata:
  name: fluentd-logzio
  namespace: monitoring
  labels:
    k8s-app: fluentd-logzio
    version: v1
spec:
 
  template:
    
    spec:
     
      tolerations:
      - key: node-role.kubernetes.io/master
        effect: NoSchedule
      # Because the image's entrypoint requires to write on /fluentd/etc but we mount configmap there which is read-only,
      # this initContainers workaround or other is needed.
      # See https://github.com/fluent/fluentd-kubernetes-daemonset/issues/90
      
      containers:
      - name: copy-fluentd-config
        image: busybox
        command: ['sh', '-c', 'cp /config-volume/..data/* /fluentd/etc']
        volumeMounts:
          - name: config-volume
            mountPath: /config-volume
          - name: fluentdconf
            mountPath: /fluentd/etc
      - name: fluentd
        image: logzio/logzio-fluentd:1.1.1
        env:
        - name: LOGZIO_LOG_SHIPPING_TOKEN
          value: logzio-log-shipping-token ## replace value here
        - name: LOGZIO_LOG_LISTENER
          value: logzio-log-listener  ## replace value here
        - name: FLUENTD_SYSTEMD_CONF
          value: "disable"
        - name: FLUENTD_PROMETHEUS_CONF
          value: "disable"
        - name: INCLUDE_NAMESPACE
          value: true
        - name: KUBERNETES_VERIFY_SSL
          value: "true"
        - name: AUDIT_LOG_FORMAT
          value: audit
        - name: "CRI"
          value: "docker"
        resources:
          limits:
            memory: 200Mi
          requests:
            cpu: 100m
            memory: 200Mi
        volumeMounts:
        - name: varlog
          mountPath: /var/log
        - name: varlibdockercontainers
          mountPath: /var/lib/docker/containers
          readOnly: true
        - name: config-volume
          mountPath: /config-volume
        - name: fluentdconf
          mountPath: /fluentd/etc
      terminationGracePeriodSeconds: 30
      volumes:
      - name: varlog
        hostPath:
          path: /var/log
      - name: varlibdockercontainers
        hostPath:
          path: /var/lib/docker/containers
      - name: config-volume
        configMap:
          name: fluentd-config
      - name: fluentdconf
        emptyDir: {}
