apiVersion: apps/v1
kind: Deployment
metadata:
  namespace:  aws-observability
  name: testbusybox
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: app-2048
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: app-2048
    spec:   
      containers:
      - name: copy-fluentd-config
        image: busybox
        command: ['sh', '-c', 'while [treu]; echo $(date); done;'] 
